### PR TITLE
Add XHR support to Bullet

### PR DESCRIPTION
**Pull request by Gasparila**
Currently Bullet console and footer warnings only work for html requests
which is a bummer for SinglePageApps and other apps that make heavy use
of AJAX or other XHR requests

### CODE REVIEW

File: lib/bullet/bullet_xhr.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+      return oldOpen.apply(this, arguments);
+    }
+    function newSend(data) {
+      if (this.onload) {
+        this._storedOnload = this.onload;
+      }
+      this.onload = newOnload;
+      return oldSend.apply(this, arguments);
+    }
+    function newOnload() {
```
Comment (uforic) [inline lib/bullet/bullet_xhr.js:16]: Do you need to store off oldOnload here?

**Review by uforic — COMMENTED** [review]
I'll leave the Ruby code to someone else, but JS looks fine; do you have any guarantees around the order of script execution? When does xhr_script get loaded?

**Review by ankurd1 — APPROVED** [review]

**Review by flexportnes — APPROVED** [review]

File: lib/bullet/rack.rb [hunk 2]
```diff
@@ -32,16 +38,10 @@ def call(env)
...
-          !response.respond_to?(:body) ||
-          !response_body(response).respond_to?(:empty?) ||
-          response_body(response).empty?
-      else
-        body = response_body(response)
-        body.nil? || body.empty?
-      end
+      # response may be ["Not Found"], ["Move Permanently"], etc, but
+      # those should not happen if the status is 200
+      body = response_body(response)
```
Comment (gretch) [inline lib/bullet/rack.rb:43]: Hi,

The new **empty?** check fails for responses with no body and first.

`undefined method `first' for #<Rack::Deflater::GzipStream:0x00007f8c53508908>
Bullet::Rack#response_body
bullet (6.0.2) lib/bullet/rack.rb, line 85
Bullet::Rack#empty?
bullet (6.0.2) lib/bullet/rack.rb, line 42`

Works fine in **bullet 5.9.0**.
